### ISSUE TITLE
Can't start :/ someone know how to fix this?

### ISSUE THREAD

**Issue by xxxjajoxxx** [Xpl0itU/pyCriptoFaucets#1]
Trying to start bot.py with python3 (3.9.4) and got this error :/ dont know how to fix it :/ can anybody help?

`----------------- ATTEMPTING ROLLS -----------------
Traceback (most recent call last):
  File "/root/pyCriptoFaucets/bot.py", line 58, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/pyCriptoFaucets/bot.py", line 25, in main
    browser = await pyppeteer.launch(headless=True, args="--lang=en")
  File "/usr/local/lib/python3.9/dist-packages/pyppeteer/launcher.py", line 306, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.9/dist-packages/pyppeteer/launcher.py", line 167, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/usr/local/lib/python3.9/dist-packages/pyppeteer/launcher.py", line 226, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pyppeteer/launcher.py", line 152, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 617, in run_until_complete
    self._check_closed()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
`

**Comment by Xpl0itU** [comment]
have you tried running it as root?

**Comment by xxxjajoxxx** [comment]
running it as a roobt in docker container

**Comment by Xpl0itU** [comment]
haven't tested it in docker, try running it outside docker
